Repository reC4P7CH4/A21-EasyContact, pull requests merged in 2021-07, with the labels that each got.

#17 DataBase - Standardize Classes
  .github/workflows/CPPCompile.yml
  .github/workflows/DataBase Test.yml
  DataBase/ContactNOGroup.h
  DataBase/DB_Export.cpp
  DataBase/DB_Export.h
  DataBase/DB_Main.cpp
  DataBase/InputFile.h
  DataBase/Merge.h
  DataBase/Priority.h
  DataBase/Weight.h
  DataBase/main.cpp
Labels: New Feature

#18 DataBase - REBASE
  DataBase/Contact.h
  DataBase/DB_Import.h
  DataBase/DB_Main.cpp
  DataBase/Priority.h
  DataBase/Weight.h
Labels: Code Style

#19 GUI - Create Interface
  .gitignore
  INSTALL.md
  README.md
  SECURITY.md
  Web/backup/main.css
  Web/backup/main.html
  Web/index.html
  Web/jquery-3.5.1.js
  Web/main_page.css
  Web/main_page.js
  Web/package-lock.json
  Web/package.json
  Web/server.js
  Web/sublink/account.css
  Web/sublink/account.html
  Web/sublink/account.js
Labels: New Feature

#20 GUI - Update Interface
  Web/index.html
  Web/main_page.js
  Web/server.js
Labels: Update

#22 WORKFLOW - DataBase CI
  .github/pull_request_template.md
  CMakeLists.txt
Labels: Update
