Repository reC4P7CH4/A21-EasyContact, pull requests merged in 2021-08, with the labels that each got.

#23 MERGE - Local Branch Update
  Web/main_page.css
Labels: Update

#25 DataBase - Email Reader
  DataBase/Contact.h
  DataBase/ContactNOGroup.h
  DataBase/ContactWithGroup.h
  DataBase/DATABASE_INCLUDE.h
  DataBase/DB_Export.h
  DataBase/DB_Import.h
  DataBase/DB_Main.cpp
  DataBase/EmailReader.h
  DataBase/Merge.h
  DataBase/Priority.h
  DataBase/Weight.h
Labels: New Feature

#28 DataBase - Import
  DataBase/ContactWithGroup.h
  DataBase/DB_Import.h
  DataBase/DB_Main.cpp
Labels: Update

#30 DataBase - Priority Sort
  DataBase/ContactNOGroup.h
  DataBase/ContactWithGroup.h
  DataBase/DATABASE_INCLUDE.h
  DataBase/DB_Main.cpp
  DataBase/EmailReader.h
  DataBase/Priority.h
  DataBase/Weight.h
Labels: New Feature

#34 GUI - Update Interface
  Web/index.html
  Web/main_page.js
  Web/server.js
Labels: Update

#36 WORKFLOW - CodeQL (JavaScript)
  .github/workflows/CodeQL.yml
Labels: New Feature

#38 DataBase - Import UPDATE
  DataBase/DB_Import.h
Labels: Update

#39 DataBase - MultiThreads (FORK --> PTHREAD)
  DataBase/DB_Import.h
  DataBase/DB_Main.cpp
  DataBase/EmailReader.h
  DataBase/Priority.h
  DataBase/README.md
Labels: Update

#42 API - BackEnd Integration
  .gitignore
  DataBase/APIAccess.h
  DataBase/APIRouter.h
  DataBase/ContactNOGroup.h
  DataBase/ContactWithGroup.h
  DataBase/DATABASE_INCLUDE.h
  DataBase/DB_Import.h
  DataBase/DB_Main.cpp
  DataBase/EmailReader.h
  DataBase/Priority.h
  DataBase/README.md
  DataBase/Weight.h
  README.md
  SECURITY.md
  Web/README.md
Labels: New Feature

#43 WORKFLOW - CodeQL (CPP)
  .github/workflows/CodeQL.yml
Labels: New Feature

#44 DataBase - Priority Sort Trigger
  DataBase/ContactWithGroup.h
  DataBase/DB_Main.cpp
  DataBase/EmailReader.h
Labels: Update

#47 HOTFIX - Main Executable
  DataBase/DB_Main.cpp
Labels: Bug

#51 HOTFIX - DataBase README
  DataBase/README.md
Labels: HOTFIX

#48 HOTFIX - Main Executable & Formate Templates
  .github/pull_request_template.md
  .github/workflows/CodeQL.yml
  DataBase/ContactNOGroup.h
  DataBase/ContactWithGroup.h
  DataBase/DATABASE_INCLUDE.h
  DataBase/DB_Main.cpp
  DataBase/ECDB.csv
  DataBase/ECDB_EM.csv
  DataBase/EM_Import.h
  DataBase/Weight.h
  DataBase/newMail.txt
Labels: HOTFIX

#53 HOTFIX - Main Executable
  DataBase/ContactNOGroup.h
  DataBase/ContactWithGroup.h
  DataBase/DB_Main.cpp
  DataBase/Weight.h
Labels: HOTFIX

#54 HOTFIX - DataBase Import
  DataBase/DB_Import.h
  DataBase/DB_Main.cpp
  DataBase/newMail.txt
Labels: HOTFIX

#56 HOTFIX - DataBase Import
  DataBase/DB_Import.h
  DataBase/DB_Main.cpp
Labels: HOTFIX

#58 DataBase - EM Import
  DataBase/DB_Main.cpp
  DataBase/EM_Import.h
Labels: New Feature

#55 WORKFLOW - CMake Performance & Clang-Format Check
  .clang-format
  .github/workflows/DB-Format.yml
  CMakeLists.txt
  DataBase/APIAccess.h
  DataBase/APIRouter.h
  DataBase/Contact.h
  DataBase/ContactNOGroup.h
  DataBase/ContactWithGroup.h
  DataBase/DATABASE_INCLUDE.h
  DataBase/DB_Export.h
  DataBase/DB_Import.h
  DataBase/DB_Main.cpp
  DataBase/EM_Import.h
  DataBase/EmailReader.h
  DataBase/Merge.h
  DataBase/Priority.h
  DataBase/Weight.h
  DataBase/apidemo.cpp
Labels: New Feature

#59 HOTFIX - DataBase Import
  DataBase/DB_Import.h
Labels: HOTFIX

#60 HOTFIX - DataBase Import
  DataBase/DB_Import.h
  DataBase/ECDB.csv
  DataBase/EM_Import.h
Labels: HOTFIX

#61 HOTFIX - README Update
  DataBase/README.md
  INSTALL.md
Labels: HOTFIX

#62 HOTFIX - Compare Contact Objects
  DataBase/APIAccess.h
  DataBase/Contact.h
  DataBase/ContactNOGroup.h
  DataBase/ContactWithGroup.h
  DataBase/DB_Main.cpp
  DataBase/apidemo.cpp
Labels: HOTFIX

#64 HOTFIX - Negative Phone Numbers
  DataBase/Contact.h
  DataBase/ContactNOGroup.h
  DataBase/DB_Import.h
  DataBase/DB_Main.cpp
Labels: HOTFIX

#66 HOTFIX - Update New Email
  DataBase/Contact.h
  DataBase/ContactNOGroup.h
  DataBase/ContactWithGroup.h
  DataBase/DB_Main.cpp
  DataBase/EmailReader.h
  DataBase/Priority.h
Labels: HOTFIX

#69 API - Route Top REWORK
  CMakeLists.txt
  DataBase/APIRouter.h
  DataBase/ContactWithGroup.h
  DataBase/README.md
  INSTALL.md
Labels: Update

#70 API - Demo Application REMOVE
  DataBase/ECDB.csv
  DataBase/ECDB_EM.csv
  DataBase/README.md
  DataBase/apidemo.cpp
  DataBase/apitest.sh
Labels: Update

#72 HOTFIX - Time Based Sorting DISABLE
  DataBase/ContactNOGroup.h
  DataBase/ContactWithGroup.h
Labels: HOTFIX

#75 INSTALLER - Ubuntu 20.04 LTS
  INSTALL.sh
  SECURITY.md
Labels: New Feature

#76 HOTFIX - Startup Time
  DataBase/ContactWithGroup.h
  DataBase/DB_Import.h
Labels: HOTFIX

#77 DataBase - Documentation UPDATE
  DataBase/APIAccess.h
  DataBase/APIRouter.h
  DataBase/ContactWithGroup.h
  DataBase/DB_Main.cpp
  DataBase/EmailReader.h
  DataBase/Priority.h
  DataBase/README.md
  DataBase/Weight.h
  README.md
Labels: Documentation
